# Generated by Django 5.2.17 on 2026-09-28 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='jinsi',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='maqsadi',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='buyi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='vazni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userdetail',
            index=models.Index(fields=['telegram_id'], name='idx_telegram_id'),
        ),
        migrations.AddIndex(
            model_name='userdetail',
            index=models.Index(fields=['user'], name='idx_user_detail_user'),
        ),
    ]
