# Generated by Django 5.2.17 on 2026-09-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='buyi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Bo'yi (sm)"),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='vazni',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Vazni (kg)'),
        ),
    ]
