# Generated by Django 5.2.17 on 2026-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userdetail_jinsi_remove_userdetail_maqsadi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
