# Generated by Django 5.2.17 on 2026-09-28 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='buyi',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='maqsadi',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='vazni',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestion',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='title',
            field=models.CharField(default='Savol', max_length=255, verbose_name='Savol sarlavhasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AICard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Karta sarlavhasi')),
                ('content', models.TextField(verbose_name='AI Javobi (Markdown)')),
                ('section_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Bo'lim nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ai_app.userquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Kartasi',
                'verbose_name_plural': 'AI Kartalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
