# Generated by Django 6.0.7 on 2026-09-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Reja nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('period_type', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], max_length=10, verbose_name='Turi')),
                ('target_date', models.DateField(verbose_name='Sana')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
            ],
        ),
    ]
