# Generated by Django 5.2.17 on 2026-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usedlogintoken_userdetail_last_login_and_more'),
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fitnessplan',
            index=models.Index(fields=['user', 'period_type', 'target_date'], name='idx_plan_user_period_date'),
        ),
    ]
